spring:
    data:
        mongodb:
            auto-index-creation: true
            username: root
            password: password
            database: upskill-db
            port: 27017
            host: localhost
            authentication-database: admin
    security:
        oauth2:
            client:
                registration:
                    auth0:
                        client-id: P614y4vJHfyGe8FEU7eOQX1qAPp70tpe
                        client-secret: SAPKOfNipjvM1ItLkoigTv7K3AKKIuaxYehKzt_koJpA8RLf5aTcStGHTjAcMTK5
                        scope:
                            - openid
                            - profile
                            - email
                    subscription:
                        authorization-grant-type: client_credentials
                        client-id: P614y4vJHfyGe8FEU7eOQX1qAPp70tpe
                        client-secret: SAPKOfNipjvM1ItLkoigTv7K3AKKIuaxYehKzt_koJpA8RLf5aTcStGHTjAcMTK5
                        token-uri: https://dev--eofa3x5.us.auth0.com/oauth/token
                provider:
                    auth0:
                        issuer-uri: https://dev--eofa3x5.us.auth0.com/
                        management-client-id: XhKXHJohHyUfS8d5po0Mnag0LPhLkkdp
                        management-client-secret: CgxZnlKmhL5qGACfxmfSt-3Hp9HEPizaTzFKrZ6_6OKP6u2v2m2iBj4r90stpNW0
                    subscription:
                        issuer-uri: https://dev--eofa3x5.us.auth0.com/
                        audience: https://todolists/api/subscription
